// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwnGEzgKq4sbQjHs6lt19nqRvsPQNh96U',
    appId: '1:290408172811:web:88627d30ffd8933cd9e60e',
    messagingSenderId: '290408172811',
    projectId: 'map-translations',
    authDomain: 'map-translations.firebaseapp.com',
    storageBucket: 'map-translations.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoKieriODvcm0t9tPI-YWvzA8_Mn84ya8',
    appId: '1:290408172811:android:879a05fbc1b35fcbd9e60e',
    messagingSenderId: '290408172811',
    projectId: 'map-translations',
    storageBucket: 'map-translations.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACFNXj1e0ubiy1Bx0WxlXv30RYByKDJHE',
    appId: '1:290408172811:ios:24433ff846738a74d9e60e',
    messagingSenderId: '290408172811',
    projectId: 'map-translations',
    storageBucket: 'map-translations.appspot.com',
    iosClientId: '290408172811-3p5b4etinleft672rp70m09cn3h1gqcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapTranslations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACFNXj1e0ubiy1Bx0WxlXv30RYByKDJHE',
    appId: '1:290408172811:ios:24433ff846738a74d9e60e',
    messagingSenderId: '290408172811',
    projectId: 'map-translations',
    storageBucket: 'map-translations.appspot.com',
    iosClientId: '290408172811-3p5b4etinleft672rp70m09cn3h1gqcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapTranslations',
  );
}
